[workspace]
authors = ["yhori991 <43234011+yhori991@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gcp-marketplace-sg4d100m"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"
jupyter = ">=1.1.1,<2"
quarto = ">=1.7.31,<2"
polars = ">=1.30.0,<2"
