[workspace]
authors = ["yhori991 <43234011+yhori991@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "gcp-marketplace-sg4d100m"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
jupyter = ">=1.1.1,<2"
